- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: import common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: copy conf folder
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart the service